services:
  mysql:
    image: mysql:8.0
    container_name: netmasters-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: netmasters_db
      MYSQL_USER: netmasters
      MYSQL_PASSWORD: netmasters_psd
    ports:
      - "3307:3306"
